apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deploy
  labels:
    app: mediawiki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediawiki
      tier: frontend
  template:
    metadata:
      labels:
        app: mediawiki
        tier: frontend
    spec:
      containers:
      - name: mediawiki
        image: mediawiki
        env:
         - name: MEDIAWIKI_SITE_SERVER
           value:
         - name: MEDIAWIKI_SITE_NAME
           value: MediaWiki
         - name: MEDIAWIKI_SITE_LANG
           value: en
         - name: MEDIAWIKI_ADMIN_USER
           value: admin
         - name: MEDIAWIKI_ADMIN_PASS
           value: admin
         - name: MEDIAWIKI_UPDATE
           value: 'true'
         - name: MEDIAWIKI_DB_TYPE
           value: mysql
         - name: MEDIAWIKI_DB_USER
           value: root
         - name: MEDIAWIKI_DB_PASSWORD
           value: password
         - name: MEDIAWIKI_DB_HOST
           value: mediawiki-mysql-svc

        ports:
        - containerPort: 80

