

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mediawiki-mysql-deploy
spec:
  selector:
   matchLabels:
    app: mediawiki
    tier: backend
  template:
    metadata:
      labels:
        app: mediawiki
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: my_wiki
            - name: MYSQL_USER
              value: wikiuser
          ports:
          - containerPort: 3306
            name: mysql
